// External Dependencies
import localFont from 'next/font/local';
import type { Metadata } from 'next';

// Local Dependencies
import './globals.css';

// Local Variables
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Type Definitions
type RootLayoutProps = {
  children: React.ReactNode;
}

// Component Definition
export default function RootLayout(props: RootLayoutProps) {
  const { children } = props;

  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
