export default [
  {
    description: 'Use KnockOut to make the most of Google Map API and MediaWiki API.',
    image: 'https://s3.amazonaws.com/i-earvin/img/neighborhood-map.jpeg',
    subheader: 'November 27, 2017',
    title: 'Neighborhood Map',
    imageTitle: 'Photo by rawpixel on Unsplash',
    link: 'http://tianyangl.com/projects/fn/neighborhood-map/index.html',
  },
  {
    description: 'Everybody knows the Memory Game. But do you know it\'s just made of two lists.',
    image: 'https://s3.amazonaws.com/i-earvin/img/memory-game.jpeg',
    subheader: 'November 26, 2017',
    title: 'Memory Game',
    imageTitle: 'Photo by Dmitri Popov on Unsplash',
    link: 'http://tianyangl.com/projects/fn/memory-game/index.html',
  },
  {
    description: 'This classic Arcade Game Clone tells us more about JavaScript\'s object-oriented-programming.',
    image: 'https://s3.amazonaws.com/i-earvin/img/arcade-game.jpeg',
    subheader: 'November 26, 2017',
    title: 'Arcade Game',
    imageTitle: 'Photo by Olivia Guastalli on Unsplash',
    link: 'http://tianyangl.com/projects/fn/arcade-game/index.html',
  },
  {
    description: 'This pixel art maker project may be a good start to learn the DOM manipulation.',
    image: 'https://s3.amazonaws.com/i-earvin/img/pixel-art-maker.jpeg',
    subheader: 'November 26, 2017',
    title: 'Pixel Art Maker',
    imageTitle: 'Photo by Al x on Unsplash',
    link: 'http://tianyangl.com/projects/fn/pixel-art-maker/index.html',
  },
  {
    description: 'What is Test-driven Development? Jasmine can tell.',
    image: 'https://s3.amazonaws.com/i-earvin/img/feed-reader-testing.jpeg',
    subheader: 'November 28, 2017',
    title: 'Feed Reader Testing',
    imageTitle: 'Photo by Helloquence on Unsplash',
    link: 'http://tianyangl.com/projects/fn/feed-reader-testing/index.html',
  },
  {
    description: 'Is it a fantastic idea to imitate how those charming solar system planets move by your CSS skills?',
    image: 'https://s3.amazonaws.com/i-earvin/img/planet-motion.jpeg',
    subheader: 'November 27, 2017',
    title: 'Planet Motion',
    imageTitle: 'Photo by David Menidrey on Unsplash',
    link: 'http://tianyangl.com/projects/udemy/orbit/orbit.html',
  },
];
